//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swagger.ORM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utenti
    {
        public int utente { get; set; }
        public string password { get; set; }
    }
}
